server:
  port: 8080

spring:
  application:
    name: ehub-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/users/**
        - id: websocket
          uri: http://user-service:8080
          predicates:
            - Path=/ws/**
        - id: websocket-events
          uri: http://event-service:8080
          predicates:
            - Path=/ws-events/**
        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/notifications/**
        - id: event-service
          uri: http://event-service:8080
          predicates:
            - Path=/events/**
        - id: keycloak
          uri: http://keycloak:8080
          predicates:
            - Path=/realms/**, /resources/**, /robots.txt
        - id: keycloak-auth
          uri: http://keycloak:8080
          predicates:
            - Path=/auth/**
