server:
  port: 8085

spring:
  application:
    name: ai-service

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models
  model: gemini-1.5-flash

logging:
  level:
    com.example.aiservice: DEBUG
